### ISSUE TITLE
not work at all.....

### ISSUE THREAD

**Issue by growerp** [billylev/flutter_posts_bloc#1]
running with 'flutter run'

result:
FAILURE: Build failed with an exception.                                
                                                                        
* What went wrong:                                                      
Execution failed for task ':app:processDebugResources'.                 
> Android resource linking failed                                       
  Output:  /home/hans/mobile/flutter/bloc_demonstration/build/app/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml:186: error: resource android:attr/fontVariationSettings not found.
  /home/hans/mobile/flutter/bloc_demonstration/build/app/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml:187: error: resource android:attr/ttcIndex not found.
  error: failed linking references.                                     
                                                                        
  Command: /home/hans/.gradle/caches/transforms-1/files-1.1/aapt2-3.2.1-4818971-linux.jar/a5130ac67751d8db7423e0bd66e3f06f/aapt2-3.2.1-4818971-linux/aapt2 link -I\
          /home/hans/Android/Sdk/platforms/android-27/android.jar\      
          --manifest\                                                   
          /home/hans/mobile/flutter/bloc_demonstration/build/app/intermediates/merged_manifests/debug/processDebugManifest/merged/AndroidManifest.xml\
          -o\                                                           
          /home/hans/mobile/flutter/bloc_demonstration/build/app/intermediates/processed_res/debug/processDebugResources/out/resources-debug.ap_\
          -R\                                                           
          @/home/hans/mobile/flutter/bloc_demonstration/build/app/intermediates/incremental/processDebugResources/resources-list-for-resources-debug.ap_.txt\
          --auto-add-overlay\                                           
          --java\                                                       
          /home/hans/mobile/flutter/bloc_demonstration/build/app/generated/not_namespaced_r_class_sources/debug/processDebugResources/r\
          --custom-package\                                             
          com.example.blocarchitecture\                                 
          -0\                                                           
          apk\                                                          
          --output-text-symbols\                                        
          /home/hans/mobile/flutter/bloc_demonstration/build/app/intermediates/symbols/debug/R.txt\
          --no-version-vectors                                          
  Daemon:  AAPT2 aapt2-3.2.1-4818971-linux Daemon #0                    
  Output:  /home/hans/.gradle/caches/transforms-1/files-1.1/support-compat-28.0.0.aar/6ebb9c5b3df2c71ac66181c3b6db3b4a/res/values/values.xml:89:5-125:25: AAPT: error: resource android:attr/fontVariationSettings not found.

**Comment by billylev** [comment]
The projects become outdated., projects recreated and run ok now.
